//! PERM (pruned-enriched Rosenbluth method) for uniform fixed polyominoes —
//! an independent, non-MCMC cross-check sampler.
//!
//! Growth: Leath-style with a deterministic FIFO discovery order.  Start
//! from a seed cell; candidates (empty sites adjacent to the cluster) are
//! processed in discovery order; each is occupied with probability p or
//! permanently blocked.  Given the FIFO rule, a fixed positioned animal A
//! containing the seed is generated by exactly one decision sequence, with
//! probability P(A) = p^(n-1) (1-p)^(b_A), where b_A counts the blocked
//! decisions made before the n-th occupation.  Importance weight
//! W = 1/P(A) makes weighted averages unbiased for the uniform ensemble,
//! and E[sum of W at size k] = k * a_k (each translation class contains the
//! seed in k positions), so PERM also estimates the animal counts a_k.
//! Weights are tracked in log space; adaptive pruning/enrichment keeps the
//! tour population flat.

use crate::Rng;

const EMPTY: u8 = 0;
const OCC: u8 = 1;
const BLOCKED: u8 = 2;
const QUEUED: u8 = 3;

/// log-sum-exp accumulator
#[derive(Clone)]
pub struct LogSum {
    m: f64,
    s: f64,
    pub count: u64,
}

impl LogSum {
    pub fn new() -> Self {
        LogSum { m: f64::NEG_INFINITY, s: 0.0, count: 0 }
    }
    pub fn add(&mut self, lw: f64) {
        self.count += 1;
        if lw > self.m {
            self.s = self.s * (self.m - lw).exp() + 1.0;
            self.m = lw;
        } else {
            self.s += (lw - self.m).exp();
        }
    }
    pub fn add_weighted(&mut self, lw: f64, v: f64) {
        // accumulate v * exp(lw), v >= 0
        if v <= 0.0 {
            return;
        }
        let l = lw + v.ln();
        self.add(l);
    }
    pub fn log_total(&self) -> f64 {
        if self.count == 0 {
            f64::NEG_INFINITY
        } else {
            self.m + self.s.ln()
        }
    }
}

pub struct Perm {
    pub n: usize,
    side: usize,
    grid: Vec<u8>,
    cand: Vec<u32>,
    cluster: Vec<u32>,
    sx: i64,
    sy: i64,
    sx2: i64,
    sy2: i64,
    p: f64,
    lp: f64,
    lq: f64,
    cplus: f64,
    cminus: f64,
    pub tours: u64,
    pub zk: Vec<LogSum>,
    pub samples: u64,
    // per-batch accumulators at size n (for error bars)
    pub nbatch: usize,
    pub batch_w: Vec<LogSum>,
    pub batch_wr: Vec<LogSum>,
    /// sum of W and of W^2 at target size, for the weight-ESS diagnostic
    pub w1: LogSum,
    pub w2: LogSum,
    cur_batch: usize,
    rng: Rng,
}

impl Perm {
    pub fn new(n: usize, p: f64, seed: u64, nbatch: usize) -> Self {
        let side = 2 * n + 5;
        Perm {
            n,
            side,
            grid: vec![EMPTY; side * side],
            cand: Vec::new(),
            cluster: Vec::new(),
            sx: 0,
            sy: 0,
            sx2: 0,
            sy2: 0,
            p,
            lp: p.ln(),
            lq: (1.0 - p).ln(),
            cplus: 3.0f64.ln(),
            cminus: 0.3f64.ln(),
            tours: 0,
            zk: vec![LogSum::new(); n + 1],
            samples: 0,
            nbatch,
            batch_w: vec![LogSum::new(); nbatch],
            batch_wr: vec![LogSum::new(); nbatch],
            w1: LogSum::new(),
            w2: LogSum::new(),
            cur_batch: 0,
            rng: Rng::new(seed),
        }
    }

    #[inline(always)]
    fn f64(&mut self) -> f64 {
        (self.rng.next_u64() >> 11) as f64 * (1.0 / (1u64 << 53) as f64)
    }

    #[inline(always)]
    fn occupy(&mut self, pos: u32) -> usize {
        // returns number of candidates appended
        self.grid[pos as usize] = OCC;
        self.cluster.push(pos);
        let (x, y) = ((pos as usize % self.side) as i64, (pos as usize / self.side) as i64);
        self.sx += x;
        self.sy += y;
        self.sx2 += x * x;
        self.sy2 += y * y;
        let w = self.side as i64;
        let mut appended = 0;
        for d in [1, -1, w, -w] {
            let q = (pos as i64 + d) as u32;
            if self.grid[q as usize] == EMPTY {
                self.grid[q as usize] = QUEUED;
                self.cand.push(q);
                appended += 1;
            }
        }
        appended
    }

    #[inline(always)]
    fn unoccupy(&mut self, pos: u32, appended: usize) {
        for _ in 0..appended {
            let q = self.cand.pop().unwrap();
            self.grid[q as usize] = EMPTY;
        }
        let (x, y) = ((pos as usize % self.side) as i64, (pos as usize / self.side) as i64);
        self.sx -= x;
        self.sy -= y;
        self.sx2 -= x * x;
        self.sy2 -= y * y;
        self.cluster.pop();
        self.grid[pos as usize] = QUEUED;
    }

    fn rg2(&self) -> f64 {
        let k = self.cluster.len() as f64;
        let mx = self.sx as f64 / k;
        let my = self.sy as f64 / k;
        (self.sx2 + self.sy2) as f64 / k - mx * mx - my * my
    }

    fn record(&mut self, lw: f64) {
        self.samples += 1;
        let r = self.rg2();
        self.batch_w[self.cur_batch].add(lw);
        self.batch_wr[self.cur_batch].add_weighted(lw, r);
        self.w1.add(lw);
        self.w2.add(2.0 * lw);
    }

    /// thresholds in log space for size k; None = no control yet
    fn thresholds(&self, k: usize) -> Option<(f64, f64)> {
        if self.tours < 100 || self.zk[k].count < 32 {
            return None;
        }
        let base = self.zk[k].log_total() - (self.tours as f64).ln();
        Some((base + self.cminus, base + self.cplus))
    }

    fn node(&mut self, t: usize, lw: f64) {
        if self.cluster.len() == self.n {
            self.record(lw);
            return;
        }
        if t == self.cand.len() {
            return; // dead end below target size
        }
        let site = self.cand[t];
        debug_assert_eq!(self.grid[site as usize], QUEUED);
        if self.f64() < self.p {
            let appended = self.occupy(site);
            let lw2 = lw - self.lp;
            let k = self.cluster.len();
            self.zk[k].add(lw2);
            match self.thresholds(k) {
                Some((lo, hi)) if k < self.n => {
                    if lw2 > hi {
                        let lw3 = lw2 - std::f64::consts::LN_2;
                        self.node(t + 1, lw3);
                        self.node(t + 1, lw3);
                    } else if lw2 < lo {
                        if self.f64() < 0.5 {
                            self.node(t + 1, lw2 + std::f64::consts::LN_2);
                        }
                    } else {
                        self.node(t + 1, lw2);
                    }
                }
                _ => self.node(t + 1, lw2),
            }
            self.unoccupy(site, appended);
        } else {
            self.grid[site as usize] = BLOCKED;
            self.node(t + 1, lw - self.lq);
            self.grid[site as usize] = QUEUED;
        }
    }

    pub fn tour(&mut self, total_tours: u64) {
        self.cur_batch = ((self.tours * self.nbatch as u64) / total_tours.max(1)) as usize;
        if self.cur_batch >= self.nbatch {
            self.cur_batch = self.nbatch - 1;
        }
        self.tours += 1;
        let mid = (self.side / 2 * self.side + self.side / 2) as u32;
        self.grid[mid as usize] = QUEUED; // so occupy() bookkeeping is uniform
        let appended = self.occupy(mid);
        self.zk[1].add(0.0);
        self.node(0, 0.0);
        self.unoccupy(mid, appended);
        self.grid[mid as usize] = EMPTY;
        debug_assert!(self.cand.is_empty() && self.cluster.is_empty());
    }

    /// log of the estimated number of FIXED animals of size k
    pub fn log_ak(&self, k: usize) -> f64 {
        self.zk[k].log_total() - (self.tours as f64).ln() - (k as f64).ln()
    }

    /// effective number of independent weights: (sum W)^2 / sum W^2
    pub fn weight_ess(&self) -> f64 {
        (2.0 * self.w1.log_total() - self.w2.log_total()).exp()
    }

    /// weighted <Rg^2> at size n with a batch-means stderr
    pub fn rg2_mean_stderr(&self) -> (f64, f64) {
        let mut w = LogSum::new();
        let mut wr = LogSum::new();
        let mut means = Vec::new();
        for b in 0..self.nbatch {
            if self.batch_w[b].count > 0 && self.batch_wr[b].count > 0 {
                means.push((self.batch_wr[b].log_total() - self.batch_w[b].log_total()).exp());
            }
            if self.batch_w[b].count > 0 {
                w.add(self.batch_w[b].log_total());
                wr.add(self.batch_wr[b].log_total());
            }
        }
        let mean = (wr.log_total() - w.log_total()).exp();
        let nb = means.len() as f64;
        let bm = means.iter().sum::<f64>() / nb;
        let var = means.iter().map(|m| (m - bm) * (m - bm)).sum::<f64>() / (nb - 1.0).max(1.0);
        (mean, (var / nb).sqrt())
    }
}
